config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


root to: "advs#index" 
get '/my-advs', to: 'home#index'
resources :advs


end

app/models/adv.rb
class Adv < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :advs, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/advs_controller.rb
class AdvsController < ApplicationController
    #   before_action :authenticate_user!

def index
    @advs = Adv.all
end
   
def show
    @adv = Adv.find(params[:id])
end
    
def new
    @adv= current_user.advs.new

end
    
def create
   @adv= current_user.advs.create(adv_params)
    
    redirect_to advs_path
end
    
def edit
    @adv = Adv.find(params[:id])
end
    
def update

    @adv = current_user.advs.find(params[:id])
    @adv.update(adv_params)
    redirect_to advs_path       
end
    
def destroy
    @adv = current_user.advs.find(params[:id])
    @adv.destroy
    redirect_to advs_path
end
    

def adv_params
    params.require(:adv).permit(:numbersofrooms,:img,:numberofbath,:area,:space,:price)
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!
  def index
    @advs = current_user.advs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/advs/_form.html.erb
hi from form 

app/views/advs/edit.html.erb
<%= form_for @adv , url:{action: "update"} do |f| %>

    <h6>NUMBERS OF ROOMS</h6>
    <%= f.text_field :numbersofrooms %>
     <br><br>
    <h6>Image</h6>
    <%= f.text_field :img %> 
    <br><br>
    <h6>NUMBERS OF BATHROOM</h6> 
    <%= f.text_field :numberofbath %>
    <br><br>
    <h6>Area</h6>
    <%= f.text_field :area %>
    <br><br>
    <h6> LAND LOT </h6>
    <%= f.text_field :space  %>
    <br><br>
    <h6>ASKING PRICE  </h6>
    <%= f.text_field :price  %>
    <br><br>


    <%=f.submit " Save " ,:class=> "btn btn-light"%>
    

    <% end %>

    

app/views/advs/index.html.erb
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
      <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
      
    </head>
    <body>
    
  
    <div class="super-container">
    <div class="row text-center" style="margin-top: 150px;">  
     <% @advs.each do |adv| %>
      <div class="stamp-sheet">
      <div class="stamp" >
      <h3 style="position: absolute;left: 10px;top:50%;color:black;background: white;"><%= adv.area%></h3>
      <a href=<%=adv_path(adv)%>>
      <img src="<%= adv.img %>" width=600 hight =400 ></a> 
    </div> 
                  
    </div>
    <% end%>

  </div> 

  </div>    
</body>
   
   
    

app/views/advs/new.html.erb
<%= form_for @adv , url:{action: "create"} do |f| %>


    <%= f.label :numbersofrooms, 'NUMBERS OF ROOMS  ' %><br>
    <%= f.text_field :numberofbath %><br><br>

    <%= f.label :img, 'Image  ' %><br>
    <%= f.text_field :img %><br><br>

    <div class="wrapper">
    <div class="box">
      <div class="js--image-preview"></div>
      <div class="upload-options">
        <label>
          <input type="file" class="image-upload" accept="image/*" />
        </label>
      </div>
    </div>

    <%= f.label :numberofbath, 'NUMBERS OF BATHROOMS  ' %><br>
    <%= f.text_field :numberofbath %><br><br>

    <%= f.label :area, 'AREA ' %><br>
    <%= f.text_field :area %><br><br>

    <%= f.label :space, 'LAND LOT ' %><br>
    <%= f.text_field :space  %><br><br>

    <%= f.label :price, 'ASKING PRICE : ' %><br>
    <%= f.text_field :price  %><br><br>

    <%= f.submit " Save " %>

    <%end%>

  
   

app/views/advs/show.html.erb
     <img style="width:400px;height:400px" src="<%= @adv.img %>"> 
     <h4> NUMBERS OF ROOMS  </h4>
     <%= @adv.numbersofrooms %> 
   
     <br>
     <h4>NUMBERS OF BATHROOMS </h4>
    <%= @adv.numberofbath %>
    <h4> AREA: </h4>
     <%= @adv.area %> 
     <br>
     <h4> LAND LOT  </h4>
     <%= @adv.space %> 
     <br>
     <h4>ASKING PRICE  </h4>
     <%= @adv.price %>
    <br>
    <% if user_signed_in?%>
<%if current_user.id == @adv.user_id %>
<br>

    <%= link_to "Edit", edit_adv_path ,:class=> "btn btn-light" %> 
    <%= link_to "Delete",adv_path(@adv),:method => :delete,:class=> "btn btn-light" %>
    




<%end%>
<%end%>

app/views/home/index.html.erb
  
    <div class="super-container">
    <div class="row text-center" style="margin-top: 150px;">  
     <% @advs.each do |adv| %>
      <div class="stamp-sheet">
      <div class="stamp" >
      <h3 style="position: absolute;left: 10px;top:50%;color:black;background: white;"><%= adv.area%></h3>
      <a href=<%=adv_path(adv)%>>
      <img src="<%= adv.img %>" width=600 hight =400 ></a> 
    </div> 
                  
    </div>
    <% end%>

  </div> 

  </div>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>

   <title>Project2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link href='https://fonts.googleapis.com/css?family=Quattrocento+Sans:400,700,400italic|Montserrat:400,700|Cardo:400italic|Advent+Pro:100' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <!-- NAVIGATION -->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
        <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          </button>
    <a class="navbar-brand scroll" href="/">Future House</a>
        </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav" style="display: flex !important;flex-direction: row;">
         </li>
        <li class="nav-item">
        <a href="/advs">Home <span class="sr-only">(current)</span></a>
        </li>
         <% if(user_signed_in?)%>  
          <li class="nav-item">
    <a href="/advs/new">Advertise</a>
          </li>
          <li class="nav-item">
    <a href="/my-advs">Your Advs </a>
          </li>
    <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete , :class => "nav-link"%>
          </li>
          <li class="nav-item">
          <%= link_to "Update my Account", edit_user_registration_path,:class => "nav-link" %>
          </li>
       <% else %>
       <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path ,:class => "nav-link"%>
          </li>
             
      <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path,:class => "nav-link" %>
              </li>
     </ul>
     </div>
     <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p> 
   
</nav>
  
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


<%= yield %>
    
</body>
</html>